"""Threads helpers ported from the upstream stdlib server."""

import json
import os
import re
import subprocess
import urllib.error
import urllib.request
from concurrent.futures import ThreadPoolExecutor
from urllib.parse import quote, urlencode

import settings
from shared import accounts_tool, cache_tool


NEGATIVE_CACHE_TTL = 120
DEFAULT_THREADS_ACCOUNTS = [
    "openai",
    "runway",
    "google",
    "meta.ai",
    "zuck",
]
IG_APP_ID_THREADS = "238260118697367"
# Default fallback doc_ids (may be stale). User-provided doc_ids in
# config/threads_doc_ids.json take priority and can be updated when
# Meta rotates them (typically every 2-4 weeks).
_DEFAULT_DOC_IDS = [
    "6232751443445612",
]
_DOC_ID_CONFIG = os.path.join(settings.CONFIG_DIR, "threads_doc_ids.json")
_DOC_ID_EXPIRED_FLAG = os.path.join(settings.CONFIG_DIR, ".threads_docid_expired")


def _load_doc_ids():
    """Load doc_ids from config file, falling back to built-in defaults."""
    try:
        with open(_DOC_ID_CONFIG) as f:
            ids = json.load(f)
            if isinstance(ids, list) and ids:
                return ids
    except (OSError, json.JSONDecodeError):
        pass
    return list(_DEFAULT_DOC_IDS)


def _flag_doc_id_expired():
    """Write a flag file and attempt to create a GitHub issue when all
    doc_ids return 'not found', indicating Meta has rotated them."""
    if os.path.exists(_DOC_ID_EXPIRED_FLAG):
        return  # already flagged this cycle
    try:
        os.makedirs(os.path.dirname(_DOC_ID_EXPIRED_FLAG), exist_ok=True)
        with open(_DOC_ID_EXPIRED_FLAG, "w") as f:
            f.write("expired")
    except OSError:
        pass
    # Auto-create GitHub issue if gh CLI is available
    try:
        # Check for existing open issue first
        check = subprocess.run(
            ["gh", "issue", "list", "--repo", "xazingatrend/trend-viewer",
             "--label", "threads-docid", "--state", "open", "--json", "number"],
            capture_output=True, timeout=10,
        )
        if check.returncode == 0 and check.stdout.strip() not in (b"", b"[]"):
            return  # issue already exists
        subprocess.run(
            ["gh", "issue", "create", "--repo", "xazingatrend/trend-viewer",
             "--title", "Threads doc_id expired - update needed",
             "--body", (
                 "All Threads GraphQL doc_ids returned 'not found'.\n"
                 "Meta has likely rotated them.\n\n"
                 "To fix: open threads.net in a browser, find the new "
                 "BarcelonaProfileThreadsTabDirectQuery doc_id in the "
                 "network tab, and update `config/threads_doc_ids.json`.\n\n"
                 "Auto-generated by trend-viewer."
             ),
             "--label", "threads-docid"],
            capture_output=True, timeout=15,
        )
    except (OSError, subprocess.TimeoutExpired):
        pass  # gh not installed or network issue - flag file is enough


def _clear_doc_id_expired():
    """Remove the expiry flag when doc_ids start working again."""
    try:
        os.remove(_DOC_ID_EXPIRED_FLAG)
    except OSError:
        pass


def register():
    accounts_tool.register_source(
        "threads", "threads_accounts.json", DEFAULT_THREADS_ACCOUNTS
    )


def _threads_lsd_and_userid(username: str):
    """Extract LSD token and user_id directly from threads.com HTML.

    This avoids the Instagram web_profile_info API which requires login.
    threads.com serves both values in the server-rendered HTML."""
    lsd = None
    user_id = None
    lsd_error = None
    user_id_error = None
    try:
        proc = subprocess.run(
            ["curl", "-sL", "https://www.threads.com/@" + quote(username)],
            capture_output=True, timeout=15,
        )
        if proc.returncode != 0:
            lsd_error = {"account": username, "kind": "parse", "code": None}
            return lsd, user_id, lsd_error, user_id_error
        html = proc.stdout.decode("utf-8", "ignore")
        lsd_match = re.search(r'"LSD",\[\],\{"token":"([^"]+)"', html)
        lsd = lsd_match.group(1) if lsd_match else None
        if not lsd:
            lsd_error = {"account": username, "kind": "parse", "code": None}
        uid_match = re.search(r'"user_id":"(\d+)"', html)
        user_id = uid_match.group(1) if uid_match else None
        if not user_id:
            user_id_error = {"account": username, "kind": "parse", "code": None}
    except subprocess.TimeoutExpired:
        lsd_error = {"account": username, "kind": "timeout", "code": None}
    except OSError:
        lsd_error = {"account": username, "kind": "http", "code": None}
    return lsd, user_id, lsd_error, user_id_error


def fetch_threads_posts(username: str):
    lsd, user_id, lsd_error, user_id_error = _threads_lsd_and_userid(username)
    if not lsd or not user_id:
        return [], user_id_error or lsd_error or {"account": username, "kind": "parse", "code": None}

    headers = {
        "X-FB-LSD": lsd,
        "X-IG-App-ID": IG_APP_ID_THREADS,
        "Sec-Fetch-Site": "same-origin",
        "X-FB-Friendly-Name": "BarcelonaProfileThreadsTabQuery",
        "Content-Type": "application/x-www-form-urlencoded",
    }
    last_error = None
    all_not_found = True
    doc_ids = _load_doc_ids()
    for doc_id in doc_ids:
        payload = urlencode(
            {
                "lsd": lsd,
                "doc_id": doc_id,
                "variables": json.dumps(
                    {
                        "userID": str(user_id),
                        "__relay_internal__pv__BarcelonaIsLoggedInrelayprovider": False,
                    }
                ),
            }
        ).encode()
        req = urllib.request.Request(
            "https://www.threads.com/api/graphql", data=payload
        )
        req.add_header("User-Agent", settings.UA)
        for key, value in headers.items():
            req.add_header(key, value)
        try:
            with urllib.request.urlopen(req, timeout=12) as resp:
                data = json.loads(resp.read().decode())
        except urllib.error.HTTPError as exc:
            last_error = {"account": username, "kind": "http", "code": exc.code}
            continue
        except TimeoutError:
            last_error = {"account": username, "kind": "timeout", "code": None}
            continue
        except urllib.error.URLError as exc:
            kind = "timeout" if isinstance(exc.reason, TimeoutError) else "http"
            last_error = {"account": username, "kind": kind, "code": None}
            continue
        except (json.JSONDecodeError, UnicodeDecodeError):
            last_error = {"account": username, "kind": "parse", "code": None}
            continue
        except OSError:
            last_error = {"account": username, "kind": "http", "code": None}
            continue
        if data.get("errors"):
            err_msg = data["errors"][0].get("message", "")
            if "not found" in err_msg.lower():
                last_error = {"account": username, "kind": "doc_id_expired", "code": None}
            else:
                all_not_found = False
                last_error = {"account": username, "kind": "parse", "code": None}
            continue
        all_not_found = False
        posts = _parse_threads(data, username)
        if posts:
            _clear_doc_id_expired()
            return posts, None
    if all_not_found and doc_ids:
        _flag_doc_id_expired()
    return [], last_error or {"account": username, "kind": "parse", "code": None}


def _parse_threads(data, username):
    posts = []

    def walk(value):
        if isinstance(value, dict):
            post = value.get("post")
            if isinstance(post, dict) and post.get("caption") is not None:
                caption = (
                    (post.get("caption") or {}).get("text", "")
                    if isinstance(post.get("caption"), dict)
                    else ""
                )
                info = post.get("text_post_app_info", {}) or {}
                images = (post.get("image_versions2") or {}).get("candidates") or []
                posts.append(
                    {
                        "account": username,
                        "text": caption[:280],
                        "likes": post.get("like_count") or 0,
                        "replies": info.get("direct_reply_count") or 0,
                        "reposts": info.get("repost_count") or 0,
                        "views": 0,
                        "media": images[0]["url"] if images else "",
                        "url": "https://www.threads.com/@%s/post/%s"
                        % (username, post.get("code", "")),
                        "createdAt": post.get("taken_at") or 0,
                    }
                )
            for nested in value.values():
                walk(nested)
        elif isinstance(value, list):
            for nested in value:
                walk(nested)

    walk(data)
    return posts


def get_threads_posts(force: bool):
    source = accounts_tool.get_source("threads")
    accounts = accounts_tool.load_accounts(source["path"], source["defaults"])
    cache_key = ("threads", tuple(accounts))

    def fetch():
        with ThreadPoolExecutor(max_workers=5) as pool:
            results = pool.map(fetch_threads_posts, accounts)
        posts = []
        errors = []
        for items, error in results:
            posts.extend(items)
            if error:
                errors.append(error)
        return posts, errors

    def ttl_for_outcome(outcome):
        posts, errors = outcome
        return NEGATIVE_CACHE_TTL if not posts and errors else None

    (posts, errors), fetched_at = cache_tool.cached(cache_key, force, fetch, ttl=ttl_for_outcome)
    return posts, accounts, fetched_at, errors, cache_tool.ttl_for(cache_key)
