"""Instagram Reels helpers -- GraphQL doc_id + /popular/ fallback."""

import json
import os
import re
import subprocess
import urllib.error
import urllib.request
from concurrent.futures import ThreadPoolExecutor
from urllib.parse import quote, urlencode

import settings
from shared import accounts_tool, cache_tool


NEGATIVE_CACHE_TTL = 120
IG_APP_ID = "936619743392459"
DEFAULT_IG_ACCOUNTS = [
    "openai",
    "runwayapp",
    "pika_labs",
    "lumalabsai",
    "midjourney",
    "klingai_official",
    "heygen_official",
    "higgsfield.ai",
    "googledeepmind",
]
# GraphQL doc_ids for PolarisProfileReelsTabContentQuery_connection.
# These rotate every 2-4 weeks. User-provided values in
# config/reels_doc_ids.json take priority.
_DEFAULT_DOC_IDS = [
    "7845543455542541",
    "25981206651899035",
]
_DOC_ID_CONFIG = os.path.join(settings.CONFIG_DIR, "reels_doc_ids.json")
_DOC_ID_EXPIRED_FLAG = os.path.join(settings.CONFIG_DIR, ".reels_docid_expired")

# /popular/ topics used as discovery fallback when GraphQL fails
_POPULAR_TOPICS = ["ai", "technology", "creators", "trending"]


def _load_doc_ids():
    """Load doc_ids from config file, falling back to built-in defaults."""
    try:
        with open(_DOC_ID_CONFIG) as f:
            ids = json.load(f)
            if isinstance(ids, list) and ids:
                return ids
    except (OSError, json.JSONDecodeError):
        pass
    return list(_DEFAULT_DOC_IDS)


def _flag_doc_id_expired():
    """Write a flag file and attempt to create a GitHub issue."""
    if os.path.exists(_DOC_ID_EXPIRED_FLAG):
        return
    try:
        os.makedirs(os.path.dirname(_DOC_ID_EXPIRED_FLAG), exist_ok=True)
        with open(_DOC_ID_EXPIRED_FLAG, "w") as f:
            f.write("expired")
    except OSError:
        pass
    try:
        check = subprocess.run(
            ["gh", "issue", "list", "--repo", "xazingatrend/trend-viewer",
             "--label", "reels-docid", "--state", "open", "--json", "number"],
            capture_output=True, timeout=10,
        )
        if check.returncode == 0 and check.stdout.strip() not in (b"", b"[]"):
            return
        subprocess.run(
            ["gh", "issue", "create", "--repo", "xazingatrend/trend-viewer",
             "--title", "Reels doc_id expired - update needed",
             "--body", (
                 "All Reels GraphQL doc_ids returned errors.\n"
                 "Instagram has likely rotated them.\n\n"
                 "To fix: inspect instagram.com network tab for the "
                 "PolarisProfileReelsTabContentQuery doc_id and update "
                 "`config/reels_doc_ids.json`.\n\n"
                 "Auto-generated by trend-viewer."
             ),
             "--label", "reels-docid"],
            capture_output=True, timeout=15,
        )
    except (OSError, subprocess.TimeoutExpired):
        pass


def _clear_doc_id_expired():
    """Remove the expiry flag when doc_ids start working again."""
    try:
        os.remove(_DOC_ID_EXPIRED_FLAG)
    except OSError:
        pass


def register():
    accounts_tool.register_source("reels", "reels_accounts.json", DEFAULT_IG_ACCOUNTS)


def _curl_ig_page(url):
    """Fetch an Instagram page via curl subprocess (TLS fingerprint bypass)."""
    try:
        proc = subprocess.run(
            ["curl", "-sL", "-H", "User-Agent: " + settings.UA, url],
            capture_output=True, timeout=15,
        )
        if proc.returncode != 0:
            return None
        return proc.stdout.decode("utf-8", "ignore")
    except (subprocess.TimeoutExpired, OSError):
        return None


def _extract_user_id(username):
    """Extract user_id from instagram.com profile page HTML."""
    html = _curl_ig_page("https://www.instagram.com/" + quote(username) + "/")
    if not html:
        return None
    m = re.search(r'"user_id"\s*:\s*"(\d+)"', html)
    if m:
        return m.group(1)
    m = re.search(r'"profilePage_(\d+)"', html)
    if m:
        return m.group(1)
    # Try embedded JSON config blob
    m = re.search(r'"pk"\s*:\s*"?(\d+)"?', html)
    if m:
        return m.group(1)
    # Try i.instagram.com API as last resort
    try:
        proc = subprocess.run(
            ["curl", "-sL",
             "-H", "User-Agent: " + settings.UA,
             "-H", "X-IG-App-ID: " + IG_APP_ID,
             "https://i.instagram.com/api/v1/users/web_profile_info/?username="
             + quote(username)],
            capture_output=True, timeout=12,
        )
        if proc.returncode == 0:
            data = json.loads(proc.stdout.decode("utf-8", "ignore"))
            uid = (data.get("data") or {}).get("user", {}).get("id")
            if uid:
                return str(uid)
    except (subprocess.TimeoutExpired, OSError, json.JSONDecodeError,
            UnicodeDecodeError):
        pass
    return None


def fetch_ig_reels_graphql(username):
    """Fetch reels for a user via Instagram GraphQL with doc_id rotation."""
    user_id = _extract_user_id(username)
    if not user_id:
        return [], {"account": username, "kind": "parse", "code": None}

    doc_ids = _load_doc_ids()
    last_error = None
    all_not_found = True

    for doc_id in doc_ids:
        payload = urlencode({
            "doc_id": doc_id,
            "variables": json.dumps({
                "userID": str(user_id),
                "data": {"include_feed_video": True, "page_size": 12,
                          "target_user_id": str(user_id)},
            }),
        }).encode()

        try:
            proc = subprocess.run(
                ["curl", "-sL", "-X", "POST",
                 "-H", "User-Agent: " + settings.UA,
                 "-H", "X-IG-App-ID: " + IG_APP_ID,
                 "-H", "Content-Type: application/x-www-form-urlencoded",
                 "-d", payload.decode(),
                 "https://www.instagram.com/graphql/query"],
                capture_output=True, timeout=15,
            )
        except (subprocess.TimeoutExpired, OSError):
            last_error = {"account": username, "kind": "timeout", "code": None}
            continue

        if proc.returncode != 0:
            last_error = {"account": username, "kind": "http", "code": None}
            continue

        try:
            data = json.loads(proc.stdout.decode("utf-8", "ignore"))
        except (json.JSONDecodeError, UnicodeDecodeError):
            last_error = {"account": username, "kind": "parse", "code": None}
            continue

        if data.get("errors"):
            err_msg = data["errors"][0].get("message", "")
            if "not found" in err_msg.lower() or "does not exist" in err_msg.lower():
                last_error = {"account": username, "kind": "doc_id_expired", "code": None}
            else:
                all_not_found = False
                last_error = {"account": username, "kind": "parse", "code": None}
            continue

        if data.get("require_login"):
            last_error = {"account": username, "kind": "http", "code": 401}
            all_not_found = False
            continue

        all_not_found = False
        reels = _parse_graphql_reels(data, username)
        if reels:
            _clear_doc_id_expired()
            return reels, None

    if all_not_found and doc_ids:
        _flag_doc_id_expired()
    return [], last_error or {"account": username, "kind": "parse", "code": None}


def _parse_graphql_reels(data, username):
    """Walk the GraphQL response tree and extract reel nodes."""
    reels = []

    def walk(value):
        if isinstance(value, dict):
            node = value
            if node.get("media") and isinstance(node["media"], dict):
                node = node["media"]
            is_video = node.get("is_video") or node.get("media_type") == 2
            shortcode = node.get("code") or node.get("shortcode")
            if is_video and shortcode:
                caption = ""
                cap = node.get("caption")
                if isinstance(cap, dict):
                    caption = (cap.get("text") or "")[:120]
                elif isinstance(cap, str):
                    caption = cap[:120]
                else:
                    edges = (node.get("edge_media_to_caption") or {}).get("edges") or []
                    if edges:
                        caption = (edges[0].get("node", {}).get("text") or "")[:120]
                thumb = (node.get("thumbnail_src") or node.get("display_url")
                         or node.get("image_versions2", {}).get("candidates", [{}])[0].get("url", ""))
                reels.append({
                    "account": username,
                    "title": caption.split("\n")[0] if caption else "(설명 없음)",
                    "views": node.get("video_view_count") or node.get("play_count") or 0,
                    "likes": (node.get("edge_liked_by") or {}).get("count",
                              node.get("like_count") or 0),
                    "comments": (node.get("edge_media_to_comment") or {}).get("count",
                                 node.get("comment_count") or 0),
                    "thumbnail": thumb,
                    "url": "https://www.instagram.com/reel/%s/" % shortcode,
                    "takenAt": node.get("taken_at_timestamp") or node.get("taken_at") or 0,
                })
                return
            for nested in value.values():
                walk(nested)
        elif isinstance(value, list):
            for nested in value:
                walk(nested)

    walk(data)
    return reels


def fetch_popular_reels():
    """Fallback: scrape /popular/{topic}/ pages for reel shortcodes."""
    reels = []
    for topic in _POPULAR_TOPICS:
        html = _curl_ig_page("https://www.instagram.com/popular/%s/" % quote(topic))
        if not html:
            continue
        codes = re.findall(r'/reel/([A-Za-z0-9_-]+)/', html)
        seen = set()
        for code in codes:
            if code in seen:
                continue
            seen.add(code)
            reels.append({
                "account": topic,
                "title": "Popular: %s" % topic,
                "views": 0,
                "likes": 0,
                "comments": 0,
                "thumbnail": "",
                "url": "https://www.instagram.com/reel/%s/" % code,
                "takenAt": 0,
            })
    return reels


def get_reels(force: bool):
    source = accounts_tool.get_source("reels")
    accounts = accounts_tool.load_accounts(source["path"], source["defaults"])
    cache_key = ("reels", tuple(accounts))

    def fetch():
        with ThreadPoolExecutor(max_workers=6) as pool:
            results = pool.map(fetch_ig_reels_graphql, accounts)
        merged = []
        errors = []
        for items, error in results:
            merged.extend(items)
            if error:
                errors.append(error)
        if not merged:
            popular = fetch_popular_reels()
            if popular:
                merged.extend(popular)
        merged.sort(key=lambda r: r["views"], reverse=True)
        return merged, errors

    def ttl_for_outcome(outcome):
        reels, errors = outcome
        return NEGATIVE_CACHE_TTL if not reels and errors else None

    (reels, errors), fetched_at = cache_tool.cached(cache_key, force, fetch, ttl=ttl_for_outcome)
    return reels, accounts, fetched_at, errors, cache_tool.ttl_for(cache_key)
